const data = '02/03/2021';
const versao = '2.0.2';

export const log_2_0_2 = [
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Ajuste atualização de data pagamento',
  },
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Inclusão item PIX no campo Forma',
  },
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Fixo',
    atividade: 'Inclusão item PIX no campo Forma',
  },
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Fixo',
    atividade: 'Inclusão campo Cartão Corporativo',
  },
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Moeda',
    atividade: 'Hide campo Padrão',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Etapa Pagamento - Inclusão item PIX no campo Forma',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Etapa Pagamento - Inclusão campo Cartão Corporativo',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Etapa Pagamento - Inclusão campo Documento',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Etapa Pagamento - Inclusão campo Número Documento',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Etapa Recebimento - Inclusão item PIX no campo Forma',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Etapa Recebimento - Inclusão campo Cartão Corporativo',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Etapa Recebimento - Inclusão campo Documento',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Etapa Recebimento - Inclusão campo Número Documento',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Etapa Tarifa - Atualiza Valor de dados origem Consolidador',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Etapa Tarifa - Inclusão campo Taxa Valor | Valores em Reais',
  },
];
