export const log_1_0_0 = [
  {
    data: '02/04/2020',
    versao: '1.0.0',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Relatório Fluxo de Caixa',
  },
  {
    data: '02/04/2020',
    versao: '1.0.0',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Relatório DRE',
  },
  {
    data: '02/04/2020',
    versao: '1.0.0',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Relatório Transação',
  },
  {
    data: '02/04/2020',
    versao: '1.0.0',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Relatório Contato',
  },
  {
    data: '02/04/2020',
    versao: '1.0.0',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Relatório Fechamento Mensal',
  },
  {
    data: '02/04/2020',
    versao: '1.0.0',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Relatório Fechamento Anual',
  },
  {
    data: '27/03/2020',
    versao: '1.0.0',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Automatização do campo Câmbio no Web Service do BACEN',
  },
  {
    data: '27/03/2020',
    versao: '1.0.0',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Atualização automatica do campo Data de Pagamento ao confirmar movimento',
  },
  {
    data: '27/03/2020',
    versao: '1.0.0',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Removida a obrigatoriedade do campo identificação do cadastro de endereços',
  },
  {
    data: '27/03/2020',
    versao: '1.0.0',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Correção do layout do cadastro de cartões na tela de pessoa física',
  },
  {
    data: '27/03/2020',
    versao: '1.0.0',
    modulo: 'GERAL',
    pagina: 'Todas',
    atividade: 'Adicionanda informações de atualização e versão no rodapé do sistema',
  },
  {
    data: '27/03/2020',
    versao: '1.0.0',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Correção do layout do cadastro de vistos na tela de pessoa física',
  },
  {
    data: '27/03/2020',
    versao: '1.0.0',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Correção do layout do cadastro de perfil na tela de pessoa física',
  },
  {
    data: '25/03/2020',
    versao: '0.9.1',
    modulo: 'SISTEMA',
    pagina: 'Bem-Vindo',
    atividade: 'Otimização de desempenho de fluxo de dados no acesso à base de dados',
  },
  {
    data: '25/03/2020',
    versao: '0.9.1',
    modulo: 'SISTEMA',
    pagina: 'Bem-Vindo',
    atividade: 'Tela bem-vindo',
  },
  {
    data: '25/03/2020',
    versao: '0.9.1',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Campo moeda automático de acordo com escolha da Conta',
  },
  {
    data: '25/03/2020',
    versao: '0.9.1',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Correção do filtro de movimentos após recarregar a página',
  },
  {
    data: '25/03/2020',
    versao: '0.9.1',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Correção do erro ao Anexar documentos',
  },
  {
    data: '25/03/2020',
    versao: '0.9.1',
    modulo: 'GERAL',
    pagina: 'Todas',
    atividade: 'Alteração da máscara de RG para permitir letras',
  },
  {
    data: '25/03/2020',
    versao: '0.9.1',
    modulo: 'TABELAS',
    pagina: 'Perfil',
    atividade: 'Correção do erro ao excluir perfil',
  },
  {
    data: '25/03/2020',
    versao: '0.9.1',
    modulo: 'FINANCEIRO',
    pagina: 'Moeda',
    atividade: 'Inclusão do campo Bacen no cadastro de Moeda',
  },
  {
    data: '25/03/2020',
    versao: '0.9.1',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Alteração do tamanho do campo Sub-grupo para visualização completa do texto',
  },
  {
    data: '25/03/2020',
    versao: '0.9.1',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Automatização do valor pago de acordo com o tipo de negociação',
  },
  {
    data: '25/03/2020',
    versao: '0.9.1',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Correção da máscara dos campos de valores',
  },
  {
    data: '25/03/2020',
    versao: '0.9.1',
    modulo: 'FINANCEIRO',
    pagina: 'Câmbio',
    atividade: 'Rotina automatizada de cadastro de Câmbio',
  },
  {
    data: '25/03/2020',
    versao: '0.9.1',
    modulo: 'FINANCEIRO',
    pagina: 'Câmbio',
    atividade: 'Cadastro de Câmbio',
  },
  {
    data: '17/03/2020',
    versao: '0.9',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Anexo de documentos financeiros',
  },
  {
    data: '17/03/2020',
    versao: '0.9',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Criada rotina de agrupamento de movimentos financeiros',
  },
  {
    data: '17/03/2020',
    versao: '0.9',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Cadastro de movimentos financeiros',
  },
  {
    data: '20/03/2020',
    versao: '0.8.4',
    modulo: 'GERAL',
    pagina: 'Todas',
    atividade: 'Criação de máscara de RG, CPF, CNPJ',
  },
  {
    data: '20/03/2020',
    versao: '0.8.4',
    modulo: 'GERAL',
    pagina: 'Todas',
    atividade: 'Correção de bug ao receber informações atrasadas ou quebradas devido a erro de conexão',
  },
  {
    data: '20/03/2020',
    versao: '0.8.4',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Filtro de CPF na tela de página',
  },
  {
    data: '20/03/2020',
    versao: '0.8.4',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Filtro de CPF na tela de página',
  },
  {
    data: '17/03/2020',
    versao: '0.8.4',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Filtro de CNPJ na tela de página',
  },
  {
    data: '17/03/2020',
    versao: '0.8.3',
    modulo: 'SISTEMA',
    pagina: 'Pessoa Jurídica',
    atividade: 'Correção do script nome p/ reserva automático',
  },
  {
    data: '17/03/2020',
    versao: '0.8.2',
    modulo: 'SISTEMA',
    pagina: 'Pessoa Jurídica',
    atividade: 'Nome p/ reserva automático',
  },
  {
    data: '17/03/2020',
    versao: '0.8.1',
    modulo: 'SISTEMA',
    pagina: 'Pessoa Física',
    atividade: 'Adicionado os campos no cadastro de pessoa física: RG, CPF, RNE, Flag Estrangeira, Nacionalidade, Aeroporto próximo',
  },
  {
    data: '17/03/2020',
    versao: '0.8.1',
    modulo: 'SISTEMA',
    pagina: 'Pessoa Física',
    atividade: "Nome do sistema 'Cataventu' na aba do navegado",
  },
  {
    data: '13/03/2020',
    versao: '0.8',
    modulo: 'SISTEMA',
    pagina: 'Pessoa Jurídica',
    atividade: 'Cadastro de Usuários',
  },
  {
    data: '13/03/2020',
    versao: '0.8',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Anexo de Documentos',
  },
  {
    data: '13/03/2020',
    versao: '0.8',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Anexo de Documentos',
  },
  {
    data: '13/03/2020',
    versao: '0.8',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Cadastro Dados Comerciais',
  },
  {
    data: '13/03/2020',
    versao: '0.8',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Cadastro Endereços',
  },
  {
    data: '13/03/2020',
    versao: '0.8',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Cadastro Contatos',
  },
  {
    data: '13/03/2020',
    versao: '0.8',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Cadastro Observaçoes',
  },
  {
    data: '13/03/2020',
    versao: '0.7.3',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Correção da máscara de celular para 16 dígitos',
  },
  {
    data: '13/03/2020',
    versao: '0.7.3',
    modulo: 'GERAL',
    pagina: 'Pessoa Física',
    atividade: 'Correção da rotina de salvar Passaportes',
  },
  {
    data: '13/03/2020',
    versao: '0.7.3',
    modulo: 'GERAL',
    pagina: 'Pessoa Física',
    atividade: 'Corrigida a validação do input de dados no campo número para permitir textos no cadastro de Cartões',
  },
  {
    data: '11/03/2020',
    versao: '0.7.2',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Correção da máscara de celular no cadastro de Contatos',
  },
  {
    data: '11/03/2020',
    versao: '0.7.2',
    modulo: 'GERAL',
    pagina: 'Pessoa Física',
    atividade: 'Correção da máscara de celular no cadastro de Emergência',
  },
  {
    data: '11/03/2020',
    versao: '0.7.2',
    modulo: 'GERAL',
    pagina: 'Pessoa Física',
    atividade: 'Corrigida a validação do input de dados no campo número para permitir textos no cadastro de Passaportes',
  },
  {
    data: '11/03/2020',
    versao: '0.7.2',
    modulo: 'GERAL',
    pagina: 'Pessoa Física',
    atividade: 'Corrigida a validação do input de dados no campo número para permitir textos no cadastro de Vistos',
  },
  {
    data: '11/03/2020',
    versao: '0.7.2',
    modulo: 'GERAL',
    pagina: 'Pessoa Física',
    atividade: 'Limite com campo Titular aumentado para 100 no cadastro de Cartões',
  },
  {
    data: '11/03/2020',
    versao: '0.7.2',
    modulo: 'GERAL',
    pagina: 'Todas',
    atividade: 'Componente react-service-worker configurado',
  },
  {
    data: '11/03/2020',
    versao: '0.7.1',
    modulo: 'GERAL',
    pagina: 'Todas',
    atividade: 'Correção do componente Auto Completar',
  },
  {
    data: '11/03/2020',
    versao: '0.7.1',
    modulo: 'GERAL',
    pagina: 'Todas',
    atividade: 'Tamanho de fonte no menu lateral',
  },
  {
    data: '06/03/2020',
    versao: '0.7',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Cadastro Observaçoes',
  },
  {
    data: '06/03/2020',
    versao: '0.7',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Cadastro Perfil',
  },
  {
    data: '06/03/2020',
    versao: '0.7',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Cadastro Cartões',
  },
  {
    data: '06/03/2020',
    versao: '0.7',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Cadastro Vistos',
  },
  {
    data: '06/03/2020',
    versao: '0.7',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Cadastro Passaportes',
  },
  {
    data: '06/03/2020',
    versao: '0.7',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Cadastro Emergência',
  },
  {
    data: '06/03/2020',
    versao: '0.7',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Cadastro Família',
  },
  {
    data: '06/03/2020',
    versao: '0.7',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Cadastro Endereços',
  },
  {
    data: '06/03/2020',
    versao: '0.7',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Cadastro Contatos',
  },
  {
    data: '06/03/2020',
    versao: '0.7',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Cadastro Dados Comerciais',
  },
  {
    data: '06/03/2020',
    versao: '0.7',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Cadastro Dados Pessoais',
  },
  {
    data: '28/02/2020',
    versao: '0.6',
    modulo: 'GERAL',
    pagina: 'Todas',
    atividade: 'Correção do Script de Filtros',
  },
  {
    data: '26/02/2020',
    versao: '0.5',
    modulo: 'TABELA',
    pagina: 'Aeroporto',
    atividade: 'Tela de Página / Ficha / Filtro',
  },
  {
    data: '26/02/2020',
    versao: '0.5',
    modulo: 'TABELA',
    pagina: 'Município',
    atividade: 'Tela de Página / Ficha / Filtro',
  },
  {
    data: '26/02/2020',
    versao: '0.5',
    modulo: 'TABELA',
    pagina: 'País',
    atividade: 'Tela de Página / Ficha / Filtro',
  },
  {
    data: '26/02/2020',
    versao: '0.5',
    modulo: 'TABELA',
    pagina: 'Perfil',
    atividade: 'Tela de Página / Ficha / Filtro',
  },
  {
    data: '26/02/2020',
    versao: '0.5',
    modulo: 'TABELA',
    pagina: 'Profissão',
    atividade: 'Tela de Página / Ficha / Filtro',
  },
  {
    data: '26/02/2020',
    versao: '0.5',
    modulo: 'TABELA',
    pagina: 'Ramo pagina',
    atividade: 'Tela de Página / Ficha / Filtro',
  },
  {
    data: '26/02/2020',
    versao: '0.5',
    modulo: 'TABELA',
    pagina: 'Serviço',
    atividade: 'Tela de Página / Ficha / Filtro',
  },
  {
    data: '26/02/2020',
    versao: '0.5',
    modulo: 'FINANCEIRO',
    pagina: 'Conta',
    atividade: 'Tela de Página / Ficha / Filtro',
  },
  {
    data: '26/02/2020',
    versao: '0.5',
    modulo: 'FINANCEIRO',
    pagina: 'Grupo',
    atividade: 'Tela de Página / Ficha / Filtro',
  },
  {
    data: '26/02/2020',
    versao: '0.5',
    modulo: 'FINANCEIRO',
    pagina: 'Moeda',
    atividade: 'Tela de Página / Ficha / Filtro',
  },
  {
    data: '26/02/2020',
    versao: '0.5',
    modulo: 'FINANCEIRO',
    pagina: 'Subgrupo',
    atividade: 'Tela de Página / Ficha / Filtro',
  },
  {
    data: '26/02/2020',
    versao: '0.5',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Tela de Página / Ficha / Filtro',
    status: 'Incompleto',
  },
  {
    data: '26/02/2020',
    versao: '0.5',
    modulo: 'SISTEMA',
    pagina: 'Usuário',
    atividade: 'Tela de Página / Ficha / Filtro',
    status: 'Incompleto',
  },
];
