export const log_1_3_0 = [
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'PROJETO',
    pagina: 'Serviços',
    atividade: 'Módulo de Serviços (Em desenvolvimento).',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'PROJETO',
    pagina: 'Serviços',
    atividade: 'Módulo Contratante.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'FINANCEIRO',
    pagina: 'Conta',
    atividade: 'Campo padrão.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'FINANCEIRO',
    pagina: 'Moeda',
    atividade: 'Campo padrão.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'SISTEMA',
    pagina: 'Parâmetros',
    atividade: 'Menu consolidador: cadastro de PF ou PJ padrão do sistema.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'SISTEMA',
    pagina: 'Parâmetros',
    atividade: 'Menu Grupo: cadastro padrão na importação/criação de novos registros.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'SISTEMA',
    pagina: 'Parâmetros',
    atividade: 'Menu Fixo: cadastro padrão na importação/criação de novos registros.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Campo Serviço.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: "Alteração da label 'Subgrupo' para 'Grupo' na tela de cadastro.",
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Campo Fornecedor: Habilita o cadastro de serviços prestados.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Campo Fornecedor: Habilita o cadastro de serviços prestados.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Correção do layout da tabela em resoluções menores na tela de Página.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Correção do layout da tabela em resoluções menores na tela de Página.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'TABELAS',
    pagina: 'Aeroporto',
    atividade: 'Correção do layout da tabela em resoluções menores na tela de Página.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'TABELAS',
    pagina: 'Tipo Cartão',
    atividade: 'Correção do layout da tabela em resoluções menores na tela de Página.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'TABELAS',
    pagina: 'Município',
    atividade: 'Correção do layout da tabela em resoluções menores na tela de Página.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'TABELAS',
    pagina: 'País',
    atividade: 'Correção do layout da tabela em resoluções menores na tela de Página.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'TABELAS',
    pagina: 'Perfil',
    atividade: 'Correção do layout da tabela em resoluções menores na tela de Página.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'TABELAS',
    pagina: 'Profissão',
    atividade: 'Correção do layout da tabela em resoluções menores na tela de Página.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'TABELAS',
    pagina: 'Ramo Atividade',
    atividade: 'Correção do layout da tabela em resoluções menores na tela de Página.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'TABELAS',
    pagina: 'Serviço',
    atividade: 'Correção do layout da tabela em resoluções menores na tela de Página.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'TABELAS',
    pagina: 'Tipo Cartão',
    atividade: 'Campo código: só em caso de cartão de crédito.',
  },
  {
    data: '09/08/2020',
    versao: '1.3.9',
    modulo: 'TABELAS',
    pagina: 'Aeroporto',
    atividade: 'Otimização de sistema: Reestruturação interna.',
  },
  {
    data: '05/07/2020',
    versao: '1.3.8',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Correção nos campos País e País de Emissão ao salvar Passaporte.',
  },
  {
    data: '05/07/2020',
    versao: '1.3.8',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Otimização de desempenho das telas de página e ficha (Hooks)',
  },
  {
    data: '05/07/2020',
    versao: '1.3.8',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Otimização de desempenho das telas de página e ficha (Hooks)',
  },
  {
    data: '05/07/2020',
    versao: '1.3.8',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Correção do botão voltar no módulo Anexar.',
  },
  {
    data: '05/07/2020',
    versao: '1.3.8',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Correção do botão voltar no módulo Anexar.',
  },
  {
    data: '05/07/2020',
    versao: '1.3.8',
    modulo: 'Financeiro',
    pagina: 'Movimento',
    atividade: 'Correção do botão voltar no módulo Anexar.',
  },
  {
    data: '05/07/2020',
    versao: '1.3.8',
    modulo: 'SISTEMA',
    pagina: 'Geral',
    atividade: 'Correção do componente Auto Completar.',
  },
  {
    data: '05/07/2020',
    versao: '1.3.8',
    modulo: 'SISTEMA',
    pagina: 'Geral',
    atividade: 'Criação do componente Auto Completar Pessoa.',
  },
  {
    data: '05/07/2020',
    versao: '1.3.8',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Padronização das tabelas em sub consultas (lista de dados).',
  },
  {
    data: '05/07/2020',
    versao: '1.3.8',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Padronização das tabelas em sub consultas (lista de dados).',
  },
  {
    data: '05/07/2020',
    versao: '1.3.8',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Padronização das tabelas em sub consultas (lista de dados).',
  },
  {
    data: '05/07/2020',
    versao: '1.3.7',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Correção da visibilidade do botão comparar na lista de movimentos.',
  },
  {
    data: '05/07/2020',
    versao: '1.3.7',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Correção da tela de Anexo (Falha na renderização).',
  },
  {
    data: '05/07/2020',
    versao: '1.3.7',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Correção ao editar movimentos agrupados (Auto completar vazio).',
  },
  {
    data: '05/07/2020',
    versao: '1.3.7',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Correção na chamado do WebService ao Gerar Fixo.',
  },
  {
    data: '05/07/2020',
    versao: '1.3.7',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Otimização de desempenho da tela de página (Hooks).',
  },
  {
    data: '05/07/2020',
    versao: '1.3.7',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Adicionado os campos Data de Vencimento Início e Fim no filtro de movimento.',
  },
  {
    data: '26/06/2020',
    versao: '1.3.6',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Otimização de desempenho da rotina - Página Principal e Fichas',
  },
  {
    data: '19/06/2020',
    versao: '1.3.5',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Consulta com links e subconsultas',
  },
  {
    data: '19/06/2020',
    versao: '1.3.5',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Consulta com links e subconsultas',
  },
  {
    data: '19/06/2020',
    versao: '1.3.5',
    modulo: 'PROJETO',
    pagina: 'Consulta',
    atividade: 'Consulta com links e subconsultas',
  },
  {
    data: '19/06/2020',
    versao: '1.3.5',
    modulo: 'FINANCEIRO',
    pagina: 'Páginas',
    atividade: 'Otimização de desempenho da rotina',
  },
  {
    data: '19/06/2020',
    versao: '1.3.5',
    modulo: 'TABELAS',
    pagina: 'Páginas',
    atividade: 'Otimização de desempenho da rotina',
  },
  {
    data: '12/06/2020',
    versao: '1.3.4',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Correção na edição de dados do Parcelamento',
  },
  {
    data: '12/06/2020',
    versao: '1.3.4',
    modulo: 'PROJETO',
    pagina: 'RSVP ',
    atividade: 'Correção comparar',
  },
  {
    data: '12/06/2020',
    versao: '1.3.4',
    modulo: 'PROJETO',
    pagina: 'Painel',
    atividade: 'Links de subconculta do projeto',
  },
  {
    data: '12/06/2020',
    versao: '1.3.4',
    modulo: 'PROJETO',
    pagina: 'Painel',
    atividade: 'Correção de inclusão do registro',
  },
  {
    data: '05/06/2020',
    versao: '1.3.3',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Correção de Component CardName',
  },
  {
    data: '05/06/2020',
    versao: '1.3.3',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Correção de Component CardName',
  },
  {
    data: '05/06/2020',
    versao: '1.3.3',
    modulo: 'PROJETO',
    pagina: 'Painel',
    atividade: 'Correção de Component CardName',
  },
  {
    data: '05/06/2020',
    versao: '1.3.2',
    modulo: 'PROJETO',
    pagina: 'Painel',
    atividade: 'Correção de Acesso ao Painel de Projetos',
  },
  {
    data: '05/06/2020',
    versao: '1.3.1',
    modulo: 'PROJETO',
    pagina: 'Ocorrências',
    atividade: 'Consulta de Ocorrências',
  },
  {
    data: '05/06/2020',
    versao: '1.3.1',
    modulo: 'PROJETO',
    pagina: 'Participantes',
    atividade: 'Recebimento de Dados na Ficha de Participantes',
  },
  {
    data: '05/06/2020',
    versao: '1.3.1',
    modulo: 'PROJETO',
    pagina: 'RSVP',
    atividade: 'Migração de Registro Comparado | Status: Confirmado',
  },
  {
    data: '05/06/2020',
    versao: '1.3.1',
    modulo: 'PROJETO',
    pagina: 'RSVP',
    atividade: 'Critério de Comparação de Registros',
  },
  {
    data: '05/06/2020',
    versao: '1.3.1',
    modulo: 'PROJETO',
    pagina: 'Painel',
    atividade: 'Links de Navegação de Telas',
  },
  {
    data: '27/05/2020',
    versao: '1.3.0',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Cadastro de Ocorrências',
  },
  {
    data: '27/05/2020',
    versao: '1.3.0',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Cadastro de Ocorrências',
  },
  {
    data: '27/05/2020',
    versao: '1.3.0',
    modulo: 'PROJETO',
    pagina: 'Ocorrências',
    atividade: 'Cadastro de Ocorrências',
  },
  {
    data: '27/05/2020',
    versao: '1.3.0',
    modulo: 'SISTEMA',
    pagina: 'Ocorrências',
    atividade: 'Cadastro de Ocorrências',
  },
  {
    data: '27/05/2020',
    versao: '1.3.0',
    modulo: 'SISTEMA',
    pagina: 'Usuários',
    atividade: 'Correção do Filtro de usuários',
  },
  {
    data: '27/05/2020',
    versao: '1.3.0',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Correção de navegação do cadastro de Pessoa Física',
  },
];
