const data = '08/03/2021';
const versao = '2.0.3';

export const log_2_0_3 = [
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Consulta com Anexo',
  },
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Correção campo Valor dos movimentos na pagina agrupamento',
  },
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Correção Campo subgrupo no agrupamento - movimento pai',
  },
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Liberação de edição do status em movimento agrupado pai - conciliado',
  },
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Fixo',
    atividade: 'Retirada de requerimento do campo Número',
  },
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Fixo',
    atividade: 'Gerar Fixo com status CONFIRMADO',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Etapa Pagamento - ajuste campo valor - completazeros',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Etapa Tarifa - Inclusão campo Extra (hospegdagem & veículo)',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Pagina - Substituição de coluna / Fornecedor & Descrição',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Inclusão do recurso Anexo',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Consulta com Anexo',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Pagina',
    atividade: 'Inclusão do recuso Anexo',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Ficha',
    atividade: 'Inclusão dos campos Responsável & Solicitante',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Consulta',
    atividade: 'Consulta com Anexo',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Consulta',
    atividade: 'Consulta com Responsável & Solicitante',
  },
  {
    data,
    versao,
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Consulta com Anexo',
  },
  {
    data,
    versao,
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Consulta com Anexo',
  },
];
