export const log_1_2_0 = [
  {
    data: '22/05/2020',
    versao: '1.2.2',
    modulo: 'PROJETO',
    pagina: 'Participantes',
    atividade: 'Consulta do cadastro de Pessoa Física',
  },
  {
    data: '22/05/2020',
    versao: '1.2.2',
    modulo: 'PROJETO',
    pagina: 'Participantes',
    atividade: 'Download de planilha da lista de Participantes',
  },
  {
    data: '22/05/2020',
    versao: '1.2.2',
    modulo: 'PROJETO',
    pagina: 'Financeiro',
    atividade: 'Aba Financeiro no painel de Projeto',
  },
  {
    data: '22/05/2020',
    versao: '1.2.2',
    modulo: 'PROJETO',
    pagina: 'Rsvp',
    atividade: 'Ficha Comparar: Botão novo cadastro de Pessoa Física',
  },
  {
    data: '22/05/2020',
    versao: '1.2.2',
    modulo: 'PROJETO',
    pagina: 'Rsvp',
    atividade: 'Adicionado o campo Notas na ficha de cadastro',
  },
  {
    data: '22/05/2020',
    versao: '1.2.2',
    modulo: 'PROJETO',
    pagina: 'Rsvp',
    atividade: 'Download de planilha da lista de RSVP',
  },
  {
    data: '22/05/2020',
    versao: '1.2.2',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Correção do layout do menu Dropdown de relatórios',
  },
  {
    data: '22/05/2020',
    versao: '1.2.2',
    modulo: 'FINANCEIRO',
    pagina: 'Fixo',
    atividade: 'Rodapé com o total dos valores da lista de movimento',
  },
  {
    data: '22/05/2020',
    versao: '1.2.2',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Rodapé com o total dos valores da lista de movimento',
  },
  {
    data: '22/05/2020',
    versao: '1.2.2',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Movimento Parcelado bloqueado para edição',
  },
  {
    data: '22/05/2020',
    versao: '1.2.2',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Otimização de desempenho do filtro do Relatório Fluxo de Caixa (localstorage)',
  },
  {
    data: '22/05/2020',
    versao: '1.2.2',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Ícone para movimentos parcelados',
  },
  {
    data: '15/05/2020',
    versao: '1.2.1',
    modulo: 'PROJETO',
    pagina: 'Rsvp',
    atividade: 'Importar lista Excel',
  },
  {
    data: '15/05/2020',
    versao: '1.2.1',
    modulo: 'PROJETO',
    pagina: 'Rsvp',
    atividade: 'Função de comparar registro do Rsvp com cadastro de Pessoa Física',
  },
  {
    data: '15/05/2020',
    versao: '1.2.1',
    modulo: 'PROJETO',
    pagina: 'Rsvp',
    atividade: 'HELP - teste de implementação de tutoriais do sistema',
  },
  {
    data: '15/05/2020',
    versao: '1.2.1',
    modulo: 'PROJETO',
    pagina: 'Rsvp',
    atividade: 'Importar RSVP para Participantes ao confirmar registro',
  },
  {
    data: '15/05/2020',
    versao: '1.2.1',
    modulo: 'GERAL',
    pagina: 'Todas',
    atividade: 'Otimização de desempenho da rotina auto-completar no acesso ao WS (Debounce)',
  },
  {
    data: '15/05/2020',
    versao: '1.2.1',
    modulo: 'GERAL',
    pagina: 'Todas',
    atividade: 'Correção das fichas de cadastro ao editar os campos',
  },
  {
    data: '15/05/2020',
    versao: '1.2.1',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Criada permissão específica para submenus do cadastro de usuários',
  },
  {
    data: '15/05/2020',
    versao: '1.2.1',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Criada permissão específica para submenus do cadastro de usuários',
  },
  {
    data: '15/05/2020',
    versao: '1.2.1',
    modulo: 'PROJETO',
    pagina: 'Projeto',
    atividade: 'Criada permissão específica para submenus do cadastro de usuários',
  },
  {
    data: '15/05/2020',
    versao: '1.2.1',
    modulo: 'FINANCEIRO',
    pagina: 'Fixo',
    atividade: 'Adicionado ícone de campo restrito na tela de página',
  },
  {
    data: '15/05/2020',
    versao: '1.2.1',
    modulo: 'FINANCEIRO',
    pagina: 'Cartão Corporativo',
    atividade: 'Correção do título na tela de ficha',
  },
  {
    data: '15/05/2020',
    versao: '1.2.1',
    modulo: 'SISTEMA',
    pagina: 'Login',
    atividade: 'Mensagem de erro na falha de comunicação com Google ou WS',
  },
  {
    data: '15/05/2020',
    versao: '1.2.1',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Correção do nome completo exibida na ficha de observação',
  },
  {
    data: '15/05/2020',
    versao: '1.2.1',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Correção do nome completo exibida na ficha de cartões',
  },
  {
    data: '05/05/2020',
    versao: '1.2.0',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Adicionado o campo Projeto no filtro de movimentos',
  },
  {
    data: '05/05/2020',
    versao: '1.2.0',
    modulo: 'PROJETO',
    pagina: 'Rsvp',
    atividade: 'Cadastro de RSVP',
  },
  {
    data: '05/05/2020',
    versao: '1.2.0',
    modulo: 'FINANCEIRO',
    pagina: 'Cartão Corporativo',
    atividade: 'Cadastro de Cartão Corporativo',
  },
  {
    data: '05/05/2020',
    versao: '1.2.0',
    modulo: 'TABELAS',
    pagina: 'Tipo Cartão',
    atividade: 'Alteração do nome Cartão para Tipo Cartão',
  },
  {
    data: '05/05/2020',
    versao: '1.2.0',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Correção do campo restrito (alinhado à direita)',
  },
  {
    data: '05/05/2020',
    versao: '1.2.0',
    modulo: 'FINANCEIRO',
    pagina: 'Parcelar',
    atividade: 'Correção do script de preenchimento das datas das Parcelas',
  },
  {
    data: '05/05/2020',
    versao: '1.2.0',
    modulo: 'FINANCEIRO',
    pagina: 'Parcelar',
    atividade: 'Correção do script de cálculo dos valores das Parcelas',
  },
  {
    data: '05/05/2020',
    versao: '1.2.0',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Adicionado o campo Cartão Corporativo na ficha de movimento',
  },
];
