const data = '01/02/2021';
const versao = '1.9.7';

export const log_1_9_7 = [
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'All',
    atividade: 'Correção casas decimais.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Orçamento',
    atividade: 'Correção na inclusão de Serviço (campo moeda inválido).',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Orçamento',
    atividade: 'Correção no Campo quantidade (soma participantes).',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Orçamento',
    atividade: 'Correção campo aprovado - editar.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Hotsite',
    atividade: 'Ajuste do tamanho do banner no Header.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Hotsite',
    atividade: 'Correção Editar formulário .',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Ficha',
    atividade: 'Correção Imagem banner vazia.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Ficha',
    atividade: 'Ajuste ocultar banner na inclusão do projeto.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Ficha',
    atividade: 'Correção campo data inicio.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Correção na edição de registros nas etapas de Pagamento e Recebimento (AC).',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Correção etapa pagamento - Inicialização do campo AC com fornecedor.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Correção na atualização de totais nas etapas de Pagamento e Recebimento.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Correção ficha - editar campo Auto Completar.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Correção link tela de consulta.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Correção etapa bilhete - edição dos registros.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Correção etapa bilhete - campo PTA.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Correção etapa tarifa - inicialização do campo AC com fornecedor.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Correção etapa tarifa - importação consolidador.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Correção etapa itinerário - edição dos registros.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Serviço',
    atividade: 'Correção datas na exportação para Movimentos Financeiros.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Tempos e Movimentos',
    atividade: 'Correção Bloqueio de anexo na inclusão de registro.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Tempos e Movimentos',
    atividade: 'Correção ao salvar primeiro registro.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Tempos e Movimentos',
    atividade: 'Correção ao Incluir anexo (cache de memória).',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Tempos e Movimentos',
    atividade: 'Correção ao Incluir direto da ficha (categoria vazia).',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Tempos e Movimentos',
    atividade: 'Correção ao Exibir serviços para vincular ao projeto.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Tempos e Movimentos',
    atividade: 'Correção no botão avançar na etapa de serviço.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Ocorrência',
    atividade: 'Correção dos campos AC na tela de inclusão (requer reset).',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Ocorrência',
    atividade: 'Correção erro página inválida.',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Ocorrência',
    atividade: 'Correção Campo Auto Completar - Projeto vazio.',
  },
  {
    data,
    versao,
    modulo: 'SISTEMA',
    pagina: 'Parâmetros',
    atividade: 'Correção Consolidador - gravar dados.',
  },
  {
    data,
    versao,
    modulo: 'SISTEMA',
    pagina: 'Ocorrência',
    atividade: 'Correção de componente Ficha de Ocorrência.',
  },
  {
    data,
    versao,
    modulo: 'SISTEMA',
    pagina: 'Parâmetros',
    atividade: 'Correção Categoria - Deletar registro.',
  },
  {
    data,
    versao,
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Correção página inválida.',
  },
  {
    data,
    versao,
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Correção - guia Cartões - máscara campo Data Validade.',
  },
  {
    data,
    versao,
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Correção - guia Contatos - máscara campo telefone.',
  },
  {
    data,
    versao,
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Correção - guia  perfil - grava - data/hora.',
  },
  {
    data,
    versao,
    modulo: 'CADASTRO',
    pagina: 'Pessoa Jurídica',
    atividade: 'Correção página inválida.',
  },
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Cartão Coorporativo',
    atividade: 'Correção - máscara campo validade.',
  },
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Correção - casas decimais | exibição campo valor negociação.',
  },
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Grupo',
    atividade: 'Correção - Filtro - campo Tipo.',
  },
  {
    data,
    versao,
    modulo: 'TABELA',
    pagina: 'Serviço',
    atividade: 'Correção - Filtro - campo Tipo.',
  },
];
