const data = '12/01/2021';
const versao = '1.9.6';

export const log_1_9_6 = [
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Adicinada cores na tela de página de acordo com a transação do movimento.',
  },
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Correção do layout da tabela em resoluções menores na tela de Página.',
  },
  {
    data,
    versao,
    modulo: 'FINANCEIRO',
    pagina: 'All',
    atividade: 'Padronização .scss para toda a estrutura do módulo nas telas de Pagina',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'All',
    atividade: 'Padronização .scss para toda a estrutura do módulo nas telas de Pagina',
  },
  {
    data,
    versao,
    modulo: 'OCORRENCIA',
    pagina: 'Componente',
    atividade: 'Correção botões de Ação - Exibir botões na tela de página',
  },
  {
    data,
    versao,
    modulo: 'PARAMETROS',
    pagina: 'CATEGORIA',
    atividade: 'Deletar registro (WS)',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'ORÇAMENTO',
    atividade: 'Campo quantidade (soma participantes)',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'SERVICOS',
    atividade: 'Erro ao salvar pagamento',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'SERVICOS',
    atividade: 'Criar tela de consulta',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'SERVICOS',
    atividade: 'Guia Pag / Rec - Atualiza novos registros',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Tempos & Movimentos',
    atividade: 'Bloqueio de anexo na inclusão de registro',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Tempos & Movimentos',
    atividade: 'CATEGORIA VAZIO (save)',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Tempos & Movimentos',
    atividade: 'Erro ao salvar primeiro registro (classlist)',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Tempos & Movimentos',
    atividade: 'Exibir serviços p/ vincular ao projeto',
  },
  {
    data,
    versao,
    modulo: 'PROJETO',
    pagina: 'Tempos & Movimentos',
    atividade: 'Incluir anexo (cache de memória)',
  },
];
