export const log_1_1_0 = [
  {
    data: '24/04/2020',
    versao: '1.1.1',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Parcelar movimentos',
  },
  {
    data: '24/04/2020',
    versao: '1.1.1',
    modulo: 'SISTEMA',
    pagina: 'Usuários',
    atividade: 'Botão replicar permissões de usuário',
  },
  {
    data: '24/04/2020',
    versao: '1.1.1',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Novas opções em forma de pagamento',
  },
  {
    data: '24/04/2020',
    versao: '1.1.1',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Novas opções em tipo de documento',
  },
  {
    data: '24/04/2020',
    versao: '1.1.1',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Campo descrição realocado para o início do formulário',
  },
  {
    data: '24/04/2020',
    versao: '1.1.1',
    modulo: 'CADASTRO',
    pagina: 'Pessoa Física',
    atividade: 'Redirect automático para a próxima etapa no cadastro de Pessoa Física (Inclusão de novo registro)',
  },
  {
    data: '24/04/2020',
    versao: '1.1.1',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Opções de vincular projetos na ficha de movimento (campo auto-completar)',
  },
  {
    data: '24/04/2020',
    versao: '1.1.1',
    modulo: 'FINANCEIRO',
    pagina: 'Movimento',
    atividade: 'Otimização de desempenho de sistema no formulário da ficha de movimento',
  },
  {
    data: '24/04/2020',
    versao: '1.1.1',
    modulo: 'GERAL',
    pagina: 'Filtro',
    atividade: 'Otimização de desempenho de sistema de todos os filtros do sistema',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'PROJETO',
    pagina: 'Participantes',
    atividade: 'Cadastro de Participantes',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'PROJETO',
    pagina: 'Projeto',
    atividade: 'Cadastro de Projeto',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'GERAL',
    pagina: 'LogIn',
    atividade: 'Login Automático',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'GERAL',
    pagina: 'Anexo',
    atividade: 'Correção de limite de tamanho no anexo',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'FINANCEIRO',
    pagina: 'Ramo Atividade',
    atividade: 'Correção de permissão de acesso',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'FINANCEIRO',
    pagina: 'Câmbio',
    atividade: 'Correção de permissão de acesso',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'FINANCEIRO',
    pagina: 'Fluxo Caixa',
    atividade: 'Correção de permissão de acesso',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'PROJETO',
    pagina: 'Projeto',
    atividade: 'Correção do auto-completar na exibição de histórico do campo',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'PROJETO',
    pagina: 'Projeto',
    atividade: 'Correção no script de permissões do usuário',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'FINANCEIRO',
    pagina: 'Fixo',
    atividade: 'Correção no script de permissões do usuário',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'TABELAS',
    pagina: 'Aeroporto',
    atividade: 'Otimização de desempenho de desempenho na consulta do registro',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'TABELAS',
    pagina: 'Cartão',
    atividade: 'Otimização de desempenho de desempenho na consulta do registro',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'TABELAS',
    pagina: 'Município',
    atividade: 'Otimização de desempenho de desempenho na consulta do registro',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'TABELAS',
    pagina: 'País',
    atividade: 'Otimização de desempenho de desempenho na consulta do registro',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'TABELAS',
    pagina: 'Perfil',
    atividade: 'Otimização de desempenho de desempenho na consulta do registro',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'TABELAS',
    pagina: 'Profissão',
    atividade: 'Otimização de desempenho de desempenho na consulta do registro',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'TABELAS',
    pagina: 'Serviço',
    atividade: 'Otimização de desempenho de desempenho na consulta do registro',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'TABELAS',
    pagina: 'Aeroporto',
    atividade: 'Otimização de desempenho de desempenho na ficha de cadastro',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'TABELAS',
    pagina: 'Cartão',
    atividade: 'Otimização de desempenho de desempenho na ficha de cadastro',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'TABELAS',
    pagina: 'Município',
    atividade: 'Otimização de desempenho de desempenho na ficha de cadastro',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'TABELAS',
    pagina: 'País',
    atividade: 'Otimização de desempenho de desempenho na ficha de cadastro',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'TABELAS',
    pagina: 'Perfil',
    atividade: 'Otimização de desempenho de desempenho na ficha de cadastro',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'TABELAS',
    pagina: 'Profissão',
    atividade: 'Otimização de desempenho de desempenho na ficha de cadastro',
  },
  {
    data: '16/04/2020',
    versao: '1.1.0',
    modulo: 'TABELAS',
    pagina: 'Serviço',
    atividade: 'Otimização de desempenho de desempenho na ficha de cadastro',
  },

];
